### ISSUE TITLE
How do I get the VDOCIPHER_PLAYBACK_TOKEN?

### ISSUE THREAD

**Issue by jasonkaplan79** [s7gm4k7ll3r/Vdocipher-Downloader#2]
The instructions say that the script should be called using:
`python decipher_dl.py --token "VDOCIPHER_PLAYBACK_TOKEN"`
How do I get the VDOCIPHER_PLAYBACK_TOKEN?

**Comment by jasonkaplan79** [comment]
I got this video URL from the HTML source:

https://player1.vdocipher.com/v2/?videoId=564a3d0de0a04f0e8904782bd544ed77&token=ChBEMFlUMDRac2RkREdVYmttEiA1NjRhM2QwZGUwYTA0ZjBlODkwNDc4MmJkNTQ0ZWQ3NyokZGExZDMyYjgtNjY1ZC00NDNlLWE5NjQtNTI2MGQyMGNjMjA2MgA45KzHtwY.POPeEmSGv1zXGIxCZ8p7enJv_8sXskBM-93E7FEyVCE

When I run the python script:

```
python3 decipher_dl.py --token "ChBEMFlUMDRac2RkREdVYmttEiA1NjRhM2QwZGUwYTA0ZjBlODkwNDc4MmJkNTQ0ZWQ3NyokZGExZDMyYjgtNjY1ZC00NDNlLWE5NjQtNTI2MGQyMGNjMjA2MgA45KzHtwY.POPeEmSGv1zXGIxCZ8p7enJv_8sXskBM-93E7FEyVCE"
/Users/jason/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "decipher_dl.py", line 282, in <module>
    asyncio.run(main(name=name, resl=resl, token=toke))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "decipher_dl.py", line 273, in main
    x = Download(name, resl, token)
  File "decipher_dl.py", line 155, in __init__
    super().__init__(token)
  File "decipher_dl.py", line 66, in __init__
    self.decode_b64(self.token)["playbackInfo"])["videoId"]
  File "decipher_dl.py", line 87, in decode_b64
    return json.loads(base64.urlsafe_b64decode(data).decode())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```



```
python3 decipher_dl.py --token "ChBEMFlUMDRac2RkREdVYmttEiA1NjRhM2QwZGUwYTA0ZjBlODkwNDc4MmJkNTQ0ZWQ3NyokZGExZDMyYjgtNjY1ZC00NDNlLWE5NjQtNTI2MGQyMGNjMjA2MgA45KzHtwY"
/Users/jason/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "decipher_dl.py", line 282, in <module>
    asyncio.run(main(name=name, resl=resl, token=toke))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "decipher_dl.py", line 273, in main
    x = Download(name, resl, token)
  File "decipher_dl.py", line 155, in __init__
    super().__init__(token)
  File "decipher_dl.py", line 66, in __init__
    self.decode_b64(self.token)["playbackInfo"])["videoId"]
  File "decipher_dl.py", line 87, in decode_b64
    return json.loads(base64.urlsafe_b64decode(data).decode())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
